services:
  bot:
    build: .
    container_name: steamdb-update-notifier-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN:?required}
    volumes:
      - type: bind
        source: ./data
        target: /app/data
